[project]
name = "CanonicalPathTools"
version = "0.1.0"
description = "Add a short description here"
authors = ["Katherine <krosenf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
